### ISSUE TITLE
Stsh schema not working

### ISSUE THREAD

**Issue by alexispurslane** [mpw/Objective-Smalltalk#2]
I open the xcworkspace in Xcode, select the stsh schema, and hit ⌘-b, to build it. It takes around 5 seconds, builds it all successfully (with 28 warnings), and yet, there is no actual stsh executable, anywhere in the project structure or in /usr/local/bin. This project looks really cool, and I really want to check it out!

**Comment by algal** [comment]
I also have not succeeded in building a functioning stsh executable, FWIW.

**Comment by alexispurslane** [comment]
I found it in: `/Users/christopherdumas/Library/Developer/Xcode/DerivedData/objective-smalltalk-fyuibyrmufbxbbaxcvekyojoozoy/Build/Products/Release`! You have to move the .frameworks to `/Library/Frameworks`, and move `stsh` to `/usr/local/bin`. Then, it works perfectly!
